<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/12/28 18:05:19
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
