<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/12/25 21:49:31

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'toor',
  'name' => 'doctrine',
)),);
